apiVersion: v1
kind: Service
metadata:
  name: product-postgres
  labels:
    app.kubernetes.io/name: product-postgres
    app.kubernetes.io/part-of: flash-sale
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: product-postgres
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
