# The Payment schema is PostgreSQL-specific Liquibase DDL. SonarCloud's generic
# SQL rules interpret PostgreSQL CHECK constraints as application-code issues
# (for example, recommending VARCHAR2 and constants inside DDL), which would
# incorrectly fail the PR reliability gate. PostgreSQL/Testcontainers and
# Liquibase remain the authoritative validation for these migrations.
sonar.exclusions=**/src/main/resources/db/changelog/**/*.sql
