apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-runtime-config
data:
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  GATEWAY_RATE_LIMIT_ENABLED: "true"
  RATE_LIMIT_ENVIRONMENT: "cloud"
  AUTHENTICATION_SERVICE_URL: "http://authentication-service:8080"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  INVENTORY_SERVICE_URL: "http://inventory-service:8080"
  CAMPAIGN_SERVICE_URL: "http://campaign-service:8080"
  FLASHSALE_SERVICE_URL: "http://flash-sale-service:8080"
  ORDER_SERVICE_URL: "http://order-service:8080"
  PAYMENT_SERVICE_URL: "http://payment-service:8080"
  JWT_ISSUER_URI: "http://authentication-service:8080"
  JWT_JWK_SET_URI: "http://authentication-service:8080/.well-known/jwks.json"
  JWT_AUDIENCE: "flash-sale-api"
  GATEWAY_CORS_ALLOWED_ORIGINS: "http://localhost:3000"
