apiVersion: v1
kind: ConfigMap
metadata:
  name: campaign-service-runtime-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/campaign_db"
  SPRING_LIQUIBASE_ENABLED: "false"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  KAFKA_AUTO_REGISTER_SCHEMAS: "false"
  JWT_ISSUER_URI: "http://authentication-service:8080"
  JWT_JWK_SET_URI: "http://authentication-service:8080/.well-known/jwks.json"
  JWT_AUDIENCE: "flash-sale-api"
  INTERNAL_JWT_AUDIENCE: "flash-sale-internal-api"
  OAUTH_TOKEN_URI: "http://authentication-service:8080/oauth2/token"
  CAMPAIGN_CLIENT_ID: "campaign-service"
  PRODUCT_SERVICE_URL: "http://product-service:8080"
  INVENTORY_SERVICE_URL: "http://inventory-service:8080"
