apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-runtime-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/inventory_db"
  LIQUIBASE_ENABLED: "false"
  JWT_ISSUER_URI: "http://authentication-service:8080"
  JWT_JWK_SET_URI: "http://authentication-service:8080/.well-known/jwks.json"
  JWT_AUDIENCE: "flash-sale-api"
  INTERNAL_JWT_AUDIENCE: "flash-sale-internal-api"
  INVENTORY_JWT_ENABLED: "true"
  INVENTORY_API_DOCS_ENABLED: "false"
