apiVersion: v1
kind: ConfigMap
metadata:
  name: inventory-service-runtime-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/inventory_db"
  LIQUIBASE_ENABLED: "false"
  JWT_ISSUER_URI: "http://authentication-service:8080"
  JWT_JWK_SET_URI: "http://authentication-service:8080/.well-known/jwks.json"
  JWT_AUDIENCE: "flash-sale-api"
  INTERNAL_JWT_AUDIENCE: "flash-sale-internal-api"
  ORDER_CLIENT_ID: "order-service"
  INVENTORY_JWT_ENABLED: "true"
  INVENTORY_API_DOCS_ENABLED: "false"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
  KAFKA_AUTO_REGISTER_SCHEMAS: "false"
  INVENTORY_REGULAR_HOLD_API_ENABLED: "false"
  INVENTORY_REGULAR_HOLD_COMMAND_CONSUMER_ENABLED: "false"
  INVENTORY_REGULAR_HOLD_OUTBOX_PUBLISHER_ENABLED: "false"
  INVENTORY_REGULAR_HOLD_EXPIRY_ENABLED: "false"
  INVENTORY_REGULAR_HOLD_TTL: "5m"
  INVENTORY_REGULAR_HOLD_COMMANDS_TOPIC: "flashsale.inventory.regular-hold.commands.v1"
  INVENTORY_REGULAR_HOLD_EVENTS_TOPIC: "flashsale.inventory.regular-hold.events.v1"
  INVENTORY_REGULAR_HOLD_COMMAND_CONSUMER_GROUP: "inventory-regular-hold-commands-v1"
  INVENTORY_REGULAR_HOLD_COMMAND_DLT_TOPIC: "flashsale.inventory.regular-hold-command.dlt.v1"
  INVENTORY_REGULAR_HOLD_RETRY_DELAYS: "1s,3s,10s"
