apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway-runtime-config.yaml
  - authentication-service-runtime-config.yaml
  - product-service-runtime-config.yaml
  - campaign-service-runtime-config.yaml
  - flash-sale-service-runtime-config.yaml
  - inventory-service-runtime-config.yaml
  - order-service-runtime-config.yaml
  - payment-service-runtime-config.yaml
