apiVersion: v1
kind: ConfigMap
metadata:
  name: product-service-runtime-config
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/product_db"
  JWT_ISSUER_URI: "http://authentication-service:8080"
  JWT_JWK_SET_URI: "http://authentication-service:8080/.well-known/jwks.json"
  JWT_AUDIENCE: "flash-sale-api"
  INTERNAL_JWT_AUDIENCE: "flash-sale-internal-api"
  ORDER_CLIENT_ID: "order-service"
