apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flash-sale-cloud
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: flash-sale
    app.kubernetes.io/managed-by: argocd
    flash-sale.environment: cloud
spec:
  project: default
  source:
    repoURL: https://github.com/phandinhphuc1234/flash-sale.git
    targetRevision: develop
    path: infra/k8s/overlays/cloud
  destination:
    server: https://kubernetes.default.svc
    namespace: flash-sale
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=false
