apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flash-sale

resources:
  - ../../base
  - flash-sale-config.yaml
  - config
  - platform

patches:
  - path: patches/api-gateway-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: api-gateway
  - path: patches/authentication-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: authentication-service
  - path: patches/product-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: product-service
  - path: patches/campaign-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: campaign-service
  - path: patches/flash-sale-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: flash-sale-service
  - path: patches/inventory-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: inventory-service
  - path: patches/order-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: order-service
  - path: patches/payment-service-envfrom.yaml
    target:
      group: apps
      version: v1
      kind: Deployment
      name: payment-service

# Phase 13 intentionally keeps the existing bootstrap tag. Later image-promotion
# workflows will update only this overlay with immutable ECR tags.
images:
  - name: api-gateway
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/api-gateway
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: authentication-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/authentication-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: campaign-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/campaign-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: flash-sale-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/flash-sale-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: inventory-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/inventory-service
    newTag: release-32093baf2350e24f48821837f82fb86b02369d56
  - name: order-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/order-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: payment-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/payment-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
  - name: product-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/product-service
    newTag: release-41de68fb88c0b4246a0c4ef9f447a620286f4e9e
