apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flash-sale

resources:
  - namespace.yaml
  - ../../base/product-postgres
  - ../../base/product-service
  - flash-sale-config.yaml

images:
  - name: product-service
    newName: 090814040069.dkr.ecr.ap-southeast-2.amazonaws.com/flash-sale/product-service
    newTag: pilot-f5fa7cb
