- op: replace
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: flash-sale-runtime-config
    - configMapRef:
        name: api-gateway-runtime-config
    - secretRef:
        name: gateway-secrets
