- op: replace
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: flash-sale-runtime-config
    - configMapRef:
        name: campaign-service-runtime-config
    - secretRef:
        name: campaign-secrets
