- op: replace
  path: /spec/template/spec/containers/0/envFrom
  value:
    - configMapRef:
        name: flash-sale-runtime-config
    - configMapRef:
        name: flash-sale-service-runtime-config
    - secretRef:
        name: flashsale-secrets
